# Generated by Django 2.2.4 on 2019-09-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('top_rank', models.IntegerField()),
                ('price', models.FloatField()),
                ('change', models.FloatField()),
                ('change_percent', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('primaryExchange', models.CharField(max_length=32)),
            ],
        ),
    ]
