# Generated by Django 2.2.6 on 2019-10-17 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('top_rank', models.IntegerField(null=True)),
                ('price', models.FloatField()),
                ('change', models.FloatField(null=True)),
                ('change_percent', models.FloatField()),
                ('market_cap', models.FloatField(null=True)),
                ('primary_exchange', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('some_field', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('job', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('my_stocks', models.CharField(blank=True, default='empty list', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
