# Generated by Django 2.2.4 on 2019-09-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='primaryExchange',
            new_name='primary_exchange',
        ),
    ]
