# Generated by Django 2.2.6 on 2019-10-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191021_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
    ]
