# Generated by Django 2.2.5 on 2019-10-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191002_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
