# Generated by Django 2.2.5 on 2019-11-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_stocks', to='myapp.Stock')),
            ],
        ),
    ]
