# Generated by Django 2.2.6 on 2019-10-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191023_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
