# Generated by Django 2.2.7 on 2019-12-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191025_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_stocks',
            field=models.CharField(blank=True, choices=[('MU', 'Micron Technology, Inc.'), ('WFC', 'Wells Fargo & Co.'), ('AMD', 'Advanced Micro Devices, Inc.'), ('BAC', 'Bank of America Corp.'), ('CHK', 'Chesapeake Energy Corp.'), ('SNAP', 'Snap, Inc.'), ('F', 'Ford Motor Co.'), ('BHGE', 'Baker Hughes, a GE Co.'), ('GE', 'General Electric Co.'), ('FCX', 'Freeport-McMoRan, Inc.'), ('AAPL', 'Apple, Inc.'), ('T', 'AT&T, Inc.'), ('MSFT', 'Microsoft Corp.'), ('ZNGA', 'Zynga, Inc.'), ('RIG', 'Transocean Ltd.'), ('HPQ', 'HP, Inc.'), ('S', 'Sprint Corp.'), ('AUY', 'Yamana Gold, Inc.'), ('ECA', 'Encana Corp.'), ('ROKU', 'Roku, Inc.')], default=[('MU', 'Micron Technology, Inc.'), ('WFC', 'Wells Fargo & Co.'), ('AMD', 'Advanced Micro Devices, Inc.'), ('BAC', 'Bank of America Corp.'), ('CHK', 'Chesapeake Energy Corp.'), ('SNAP', 'Snap, Inc.'), ('F', 'Ford Motor Co.'), ('BHGE', 'Baker Hughes, a GE Co.'), ('GE', 'General Electric Co.'), ('FCX', 'Freeport-McMoRan, Inc.'), ('AAPL', 'Apple, Inc.'), ('T', 'AT&T, Inc.'), ('MSFT', 'Microsoft Corp.'), ('ZNGA', 'Zynga, Inc.'), ('RIG', 'Transocean Ltd.'), ('HPQ', 'HP, Inc.'), ('S', 'Sprint Corp.'), ('AUY', 'Yamana Gold, Inc.'), ('ECA', 'Encana Corp.'), ('ROKU', 'Roku, Inc.')], max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_symbol', to='myapp.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='FollowedStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_stocks', to='myapp.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.Stock')),
            ],
        ),
    ]
