# Generated by Django 2.2.5 on 2019-10-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191003_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Handbooks and manuals by discipline', 'Handbooks and manuals by discipline'), ('Business books', 'Business books'), ('Books of literary criticism', 'Books of literary criticism'), ('Books about literary theory', 'Books about literary theory'), ('Books about literature', 'Books about literature')], max_length=100)),
            ],
        ),
    ]
