# Generated by Django 2.2.7 on 2019-12-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191216_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='my_stocks',
        ),
    ]
