# Generated by Django 2.2.5 on 2019-10-07 11:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Handbooks and manuals by discipline', 'Handbooks and manuals by discipline'), ('Business books', 'Business books'), ('Books of literary criticism', 'Books of literary criticism'), ('Books about literary theory', 'Books about literary theory'), ('Books about literature', 'Books about literature')], max_length=129),
        ),
    ]
