# Generated by Django 2.2.7 on 2019-12-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profile_my_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_stocks',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
