# Generated by Django 2.2.5 on 2019-10-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191008_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_stocks',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
