# Generated by Django 2.2.5 on 2019-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20191008_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_stocks',
            field=models.CharField(choices=[('MU', 'Micron Technology, Inc.'), ('WFC', 'Wells Fargo & Co.'), ('AMD', 'Advanced Micro Devices, Inc.'), ('BAC', 'Bank of America Corp.'), ('CHK', 'Chesapeake Energy Corp.'), ('SNAP', 'Snap, Inc.'), ('F', 'Ford Motor Co.'), ('BHGE', 'Baker Hughes, a GE Co.'), ('GE', 'General Electric Co.'), ('FCX', 'Freeport-McMoRan, Inc.'), ('AAPL', 'Apple, Inc.'), ('T', 'AT&T, Inc.'), ('MSFT', 'Microsoft Corp.'), ('ZNGA', 'Zynga, Inc.'), ('RIG', 'Transocean Ltd.'), ('HPQ', 'HP, Inc.'), ('S', 'Sprint Corp.'), ('AUY', 'Yamana Gold, Inc.'), ('ECA', 'Encana Corp.'), ('ROKU', 'Roku, Inc.')], default='empty list', max_length=100),
        ),
    ]
