# Generated by Django 2.2.5 on 2019-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20191008_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_stocks',
            field=models.CharField(blank=True, choices=[('Micron Technology, Inc.', 'MU'), ('Wells Fargo & Co.', 'WFC'), ('Advanced Micro Devices, Inc.', 'AMD'), ('Bank of America Corp.', 'BAC'), ('Chesapeake Energy Corp.', 'CHK'), ('Snap, Inc.', 'SNAP'), ('Ford Motor Co.', 'F'), ('Baker Hughes, a GE Co.', 'BHGE'), ('General Electric Co.', 'GE'), ('Freeport-McMoRan, Inc.', 'FCX'), ('Apple, Inc.', 'AAPL'), ('AT&T, Inc.', 'T'), ('Microsoft Corp.', 'MSFT'), ('Zynga, Inc.', 'ZNGA'), ('Transocean Ltd.', 'RIG'), ('HP, Inc.', 'HPQ'), ('Sprint Corp.', 'S'), ('Yamana Gold, Inc.', 'AUY'), ('Encana Corp.', 'ECA'), ('Roku, Inc.', 'ROKU')], default='empty list', max_length=100),
        ),
    ]
