# Generated by Django 2.2.5 on 2019-10-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20191010_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
    ]
